# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  repositories:
  # The name used to reference this repository in the checkout step
  - repository: BashCalcRepo 
    type: github
    endpoint: qinjusGithub
    name: yuanqin333/bashCalc
# The name used to reference this repository in the checkout step
  - repository: WindowsBatchRepo
    type: github
    endpoint: qinjusGithub
    name: yuanqin333/winBatch

trigger:
- master

stages:
  - 
#First Stage on Ubuntu
- stage: UbuntuQAEnvCheck
  jobs:
  - job: InlineScripts
  
      pool:
        vmImage: 'ubuntu-latest'

      steps:
        checkout: none
      - script: echo Hello, world!
        displayName: 'Run a one-line script'

      - script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
        displayName: 'Run a multi-line script'
